#!/bin/bash

# Update and upgrade system packages
sudo yum update
sudo yum upgrade

# Download and extract Go
wget https://go.dev/dl/go1.21.5.linux-amd64.tar.gz
tar -xvf go1.21.5.linux-amd64.tar.gz

# Move Go to the system directory
sudo mv go /usr/local

# Set up Go environment variables
echo 'export GOROOT=/usr/local/go' >> ~/.bashrc
echo 'export GOPATH=$HOME/go' >> ~/.bashrc
echo 'export PATH=$PATH:$GOROOT/bin:$GOPATH/bin' >> ~/.bashrc
source ~/.bashrc

# Install xcaddy
go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

# Build Caddy with Route 53 DNS plugin
xcaddy build --with github.com/caddy-dns/route53

# Create Caddyfile
mkdir /etc/caddy && touch /etc/caddy/Caddyfile

# Allow low port listening
sudo setcap CAP_NET_BIND_SERVICE=+eip $(which caddy)

# Move Caddy to the system binaries directory
sudo mv caddy /usr/bin

# Create a caddy group
sudo groupadd --system caddy

# Create a user named caddy with a writeable home directory
sudo useradd --system \
    --gid caddy \
    --create-home \
    --home-dir /var/lib/caddy \
    --shell /usr/sbin/nologin \
    --comment "Caddy web server" \
    caddy

# Collect systemctl unit file
wget https://raw.githubusercontent.com/caddyserver/dist/master/init/caddy.service

# Move the service unit file to systemctl location
sudo mv caddy.service /etc/systemd/system/

# Make sure is executable
sudo chmod 644 /etc/systemd/system/caddy.service

# Start caddy service
sudo systemctl daemon-reload
sudo systemctl enable caddy.service
sudo systemctl start caddy.service
